[project]
name = "qrl-pong"
version = "0.1.0"
description = "Simple quantum-classical-hybrid agent to play the Atari game Pong"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas>=2.3.1",
    "pennylane>=0.41.1",
    "pufferlib>=3.0.0",
    "scienceplots>=2.1.1",
    "seaborn>=0.13.2",
    "tbparse>=0.0.9",
    "tensorboard>=2.20.0",
    "torch>=2.7.1",
    "torchaudio>=2.7.1",
    "torchvision>=0.22.1",
    "tyro>=0.9.26",
    "wandb>=0.21.0",
]

[tool.uv]
cache-dir = "./.uv_cache"
