[project]
name = "qrl-pong"
version = "0.1.0"
description = "Simple quantum-classical-hybrid agent to play the Atari game Pong"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pennylane>=0.41.1",
    "pufferlib>=3.0.0",
    "torch>=2.7.1",
    "torchaudio>=2.7.1",
    "torchvision>=0.22.1",
    "tyro>=0.9.26",
    "wandb>=0.21.0",
]
