[project]
name = "qrl-pong"
version = "0.1.0"
description = "Simple quantum-classical-hybrid agent to play the Atari game Pong"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ale-py>=0.10.2",
    "autorom>=0.6.1",
    "flax>=0.10.5",
    "gymnasium[all]>=1.1.1",
    "jax[cuda12]>=0.5.3",
    "multi-agent-ale-py>=0.1.11",
    "pennylane>=0.41.0",
    "pettingzoo>=1.24.3",
    "skrl>=1.4.3",
    "supersuit>=3.9.3",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
    "tyro>=0.9.19",
    "wandb>=0.19.9",
]
